name: whatsapp-adapter
services:
  app:
    container_name: whatsapp-adapter
    environment:
      - MONGO_HOST=mongodb
      - MINIO_HOST=minio
      - RABBITMQ_HOST=rabbitmq
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    volumes:
      - ./auth_info_baileys:/app/auth_info_baileys

  minio:
    image: minio/minio
    container_name: whatsapp-adapter-minio
    restart: always
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_ADMIN_PORT}:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 30s
      timeout: 20s
      retries: 3
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    env_file:
      - .env
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672"

volumes:
  minio_data:
  temp:
    driver: local
