export enum MessageTypeEnum {
  Image = "imageMessage",
  Video = "videoMessage",
  Audio = "audioMessage",
  Document = "documentMessage",
  DocumentWithCaption = "documentWithCaptionMessage",
  Location = "locationMessage",
  LiveLocation = "liveLocationMessage",
  Contact = "contactMessage",
  Reaction = "reactionMessage",
  ExtendedText = "extendedTextMessage",
  Protocol_Message = "protocolMessage",
  Conversation = "conversation",
  Unknown = "unknown",
}
